project:
  type: book
  output-dir: docs

book:
  title: "自然保护地景观生态学规划实验教程"
  author: "王原"
  date: "02/14/2025"
  chapters:
    - index.qmd
    - 01_intro.qmd
    - 02_portfolio.qmd
    - 99_references.qmd
  sidebar:
    title: "生态规划课程"
    style: "floating"
    background: "light"
    tools:
      - icon: github
        href: https://github.com/
      - icon: linkedin
        href: https://www.linkedin.com/in/

bibliography: learning_diary.bib

format:
  html:
    theme: pulse
  pdf:
    documentclass: scrreprt

editor: visual

